all: pi0

pi0: pi0.c
	gcc -O3 -fopenmp $^ -o $@

pi1: pi1.c
	gcc -O3 -fopenmp $^ -o $@

pi2: pi2.c
	gcc -O3 -fopenmp $^ -o $@

pi3: pi3.c
	gcc -O3 -fopenmp $^ -o $@

pi4: pi4.c
	gcc -O3 -fopenmp $^ -o $@

pi5: pi5.c
	gcc -O3 -fopenmp $^ -o $@

clean:
	rm -rf pi{0,1,2,3,4,5}

